sudo: false
language: python
python:
  - '2.7'

env:
  global:
    - DATABASE_URL=postgresql://localhost/flask_psi_test
    - TEST_DATABASE_URL=postgresql://localhost/flask_psi_test
    - TESTING="True"

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE flask_psi_test;'

before_install:
  - pip install codecov

install:
  - pip install -r requirements/test.txt

script:
  - nosetests -w tests --with-coverage --cover-erase --with-xunit --cover-branches --xunit-file=nosetests.xml

after_success:
  - codecov
