sudo: false
language: python
python:
  - '2.7'

env:
  global:
    - DATABASE_URL=postgresql://localhost/flask_psi_test
    - TEST_DATABASE_URL=postgresql://localhost/flask_psi_test
    - TESTING="True"

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE flask_psi_test;'

before_install:
  - pip install codecov

install:
  - pip install -r test_requirements.txt

script:
  - python manage.py test

after_success:
  - codecov

deploy:
  - provider: openshift
    skip_cleanup: true
    user: $OPENSHIFT_USER
    password: $OPENSHIFT_PASS
    domain: betterlife
    app: dstore
    on:
      all_branches: true
  - provider: openshift
    skip_cleanup: true
    user: $OPENSHIFT_USER
    password: $OPENSHIFT_PASS
    domain: betterlife
    app: store
    on:
      tags: true
