sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - WTFORMS_VERSION=1
  - WTFORMS_VERSION=2

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE flask-psi-test;'

install:
  - pip install -r test_requirements.txt

script: ./run_tests.sh
