sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DATABASE_URL=postgres://postgres@localhost:5432/flask_psi_test

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE flask_psi_test;'

install:
  - pip install -r test_requirements.txt

script: ./run_tests.sh
