sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DATABASE_URL=postgres://postgres@localhost:5432/flask_psi_test
  - TESTING="True"

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE flask_psi_test;'

install:
  - pip install -r test_requirements.txt
  - python manage.py db upgrade

script:
  - nosetests -w tests --with-coverage --cover-erase --with-xunit --cover-branches
  - bash <(curl -s https://codecov.io/bash) -t b0607487-ef58-48c2-9efa-8538b24fcdfd
