sudo: false
language: python
cache: pip
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
python:
  - 3.4
  - 3.5
  - 3.6
  - "pypy3.5"
env: # important, without the top-level env, no job will be allowed to fail.
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
  allow_failures:
    - python: "pypy3.5"
env:
  global:
    - DATABASE_URL=postgresql://localhost/flask_psi_test
    - TEST_DATABASE_URL=postgresql://localhost/flask_psi_test
    - TESTING="True"
    - CODECLIMATE_REPO_TOKEN=b66ce794c42bc566d01713825caa2dfd117ba2b8e67e17dcb64ebb85dd2655ba
services:
  - postgresql
before_script:
  - psql -U postgres -c 'CREATE DATABASE flask_psi_test;'
before_install:
  - pip install codecov
install:
  - pip install -r requirements/test.txt
  - pip install codeclimate-test-reporter
  - mv setup.cfg.template setup.cfg
  - mv psi/migrations/alembic.ini.template psi/migrations/alembic.ini
  - mkdir -p psi/app/static/uploaded
script:
  - if [[ $TRAVIS_PYTHON_VERSION == "pypy3.5" ]]; then (pip install -r requirements/common-pypy.txt); fi
  - nosetests tests --with-coverage --cover-erase --cover-branches --with-xunit --xunit-file=nosetests.xml
after_success:
  - codeclimate-test-reporter
  - export BUILD_DATE_FORMAT="+%Y-%m-%d"
  - export BUILD_DATE=`date $BUILD_DATE_FORMAT`
  - echo "$TRAVIS_COMMIT $TRAVIS_BUILD_NUMBER $TRAVIS_BUILD_ID $TRAVIS_BRANCH $TRAVIS_TAG $BUILD_DATE"
  - echo "$TRAVIS_COMMIT $TRAVIS_BUILD_NUMBER $TRAVIS_BUILD_ID $TRAVIS_BRANCH $TRAVIS_TAG $BUILD_DATE" > swtag
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then (codecov); fi
